### ISSUE TITLE
What does it mean when Rancher certificate shows "Common Name (CN)	dynamiclistener-ca"

### ISSUE THREAD

**Issue by ainiml** [rancher/dynamiclistener#24]
https://github.com/rancher/dynamiclistener/blob/52ede5ec92345823115cb4dc2c2b15931f572a1f/factory/ca.go#L19

![image](https://user-images.githubusercontent.com/28725423/81128867-71388680-8f10-11ea-9ba4-af7454afce98.png)

**Comment by brandond** [comment]
It's just using a self-signed CA to secure communication between internal components. The names are not particularly significant, other than that they can be useful to identify what component us using those certs. If you have any specific questions about how or why it's doing this you might drop by on Slack.
